
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ULLAS
 */
public class details extends javax.swing.JFrame {
  
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public details(int id) {
        initComponents();
        
        setDefaultCloseOperation(details.DISPOSE_ON_CLOSE);
     
        
        
        try{
         con = DriverManager.getConnection("jdbc:mysql://localhost/bd doctors","root","");
     
         String sql = "SELECT `ID`, `Doctors_Name`, `Specialist`, `Hospital`, `Time_Telephone_no`, `Address`, `District` FROM `users` WHERE ID="+id+"";
         pst = con.prepareStatement(sql);
         
         rs=pst.executeQuery();
         
         while (rs.next()) {
             String d = rs.getString("Doctors_Name");
             String e = rs.getString("Specialist");
             String f = rs.getString("Hospital");
             String g = rs.getString("Time_Telephone_no");
             String h = rs.getString("Address");
             String i = rs.getString("District");
             
             dName.setText(d);
             sName.setText(e);
             adName.setText(f);
             ttName.setText(g);
             dsName.setText(h);
             hsName.setText(i);
         }
         
         
     }
     catch(SQLException ex){
         JOptionPane.showMessageDialog(null, ex);
   
     }

        
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dName = new javax.swing.JLabel();
        adName = new javax.swing.JLabel();
        sName = new javax.swing.JLabel();
        ttName = new javax.swing.JLabel();
        dsName = new javax.swing.JLabel();
        hsName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 231, 216));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 3))); // NOI18N
        jPanel1.setLayout(null);

        dName.setBackground(new java.awt.Color(255, 255, 255));
        dName.setFont(dName.getFont().deriveFont(dName.getFont().getStyle() | java.awt.Font.BOLD, dName.getFont().getSize()+17));
        dName.setForeground(new java.awt.Color(51, 0, 153));
        dName.setText("Dn");
        jPanel1.add(dName);
        dName.setBounds(100, 141, 1140, 50);

        adName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        adName.setText("AD");
        jPanel1.add(adName);
        adName.setBounds(100, 250, 1140, 31);

        sName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sName.setText("Sp");
        jPanel1.add(sName);
        sName.setBounds(100, 200, 1140, 32);

        ttName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ttName.setText("TT");
        jPanel1.add(ttName);
        ttName.setBounds(100, 290, 1140, 31);

        dsName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dsName.setText("Ds");
        jPanel1.add(dsName);
        dsName.setBounds(100, 330, 1140, 31);

        hsName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hsName.setText("HS");
        jPanel1.add(hsName);
        hsName.setBounds(100, 370, 1140, 36);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("--------Doctor's_Details---------");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 40, 510, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1249, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1271, 530));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adName;
    private javax.swing.JLabel dName;
    private javax.swing.JLabel dsName;
    private javax.swing.JLabel hsName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel sName;
    private javax.swing.JLabel ttName;
    // End of variables declaration//GEN-END:variables

}
