
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ULLAS
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form LoginTest
     */
    public Login() {

        initComponents();
        UIManager.put("OptionPane.minimumSize", new Dimension(400, 180));
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(
                "Cambria Math", Font.PLAIN, 25)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Please Login For Enter Main Menu");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 90, 570, 70);

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getSize()+16f));
        jLabel2.setText("password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 360, 150, 50);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()+16f));
        jLabel1.setText("username");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 270, 160, 50);

        username.setBackground(new java.awt.Color(230, 255, 255));
        username.setFont(username.getFont().deriveFont(username.getFont().getSize()+21f));
        username.setForeground(new java.awt.Color(153, 0, 204));
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameKeyPressed(evt);
            }
        });
        jPanel1.add(username);
        username.setBounds(250, 270, 300, 50);

        password.setBackground(new java.awt.Color(230, 255, 255));
        password.setFont(new java.awt.Font("Tahoma", 1, 37)); // NOI18N
        password.setForeground(new java.awt.Color(153, 0, 204));
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });
        jPanel1.add(password);
        password.setBounds(250, 360, 300, 50);

        login.setBackground(new java.awt.Color(252, 229, 206));
        login.setFont(login.getFont().deriveFont(login.getFont().getSize()+18f));
        login.setText("login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login);
        login.setBounds(250, 470, 140, 50);

        reset.setBackground(new java.awt.Color(252, 229, 206));
        reset.setFont(reset.getFont().deriveFont(reset.getFont().getSize()+18f));
        reset.setText("clear");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset);
        reset.setBounds(420, 470, 130, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ULLAS\\Desktop\\project\\image\\bigstock-Medical-physician-doctor-hands-84721406.jpg")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, -20, 1380, 810);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1298, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1320, 814));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        try {
            
             Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_blog_batch18", "root", "");
                String sql = "Select * from tbl_worker where worker_name=? and worker_password=? ";
                String sql2 = "Select * from tbl_worker where worker_Email=? and worker_password=? ";
                PreparedStatement pst = con.prepareStatement(sql);
                PreparedStatement pst2 = con.prepareStatement(sql2);
                pst.setString(1, username.getText());
                pst.setString(2, password.getText());
                pst2.setString(1, username.getText());
                pst2.setString(2, password.getText());
                ResultSet rs = pst.executeQuery();
                ResultSet rs2 = pst2.executeQuery();
                if (rs.next() || rs2.next()) {
                Main ts = new Main();
                ts.setVisible(true);
                setVisible(false);
                JOptionPane.showMessageDialog(null, "Successfully loged in !");

            } else if (username.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Type Username Field !");
            } else if (password.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Type Password Field !");
            } else {
                JOptionPane.showMessageDialog(null, "Wrong Username Or Password !");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_loginActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        username.setText("");
        password.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_blog_batch18", "root", "");
                String sql = "Select * from tbl_worker where worker_name=? and worker_password=? ";
                String sql2 = "Select * from tbl_worker where worker_Email=? and worker_password=? ";
                PreparedStatement pst = con.prepareStatement(sql);
                PreparedStatement pst2 = con.prepareStatement(sql2);
                pst.setString(1, username.getText());
                pst.setString(2, password.getText());
                pst2.setString(1, username.getText());
                pst2.setString(2, password.getText());
                ResultSet rs = pst.executeQuery();
                ResultSet rs2 = pst2.executeQuery();
                if (rs.next() || rs2.next()) {
                    
                    Main ts = new Main();
                    ts.setVisible(true);
                    setVisible(false);
                    JOptionPane.showMessageDialog(null, "Successfully loged in !");
                }else if (password.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Type Password Field !");
                }
                else {
                    JOptionPane.showMessageDialog(null, "Wrong Username Or Password !");
                }
              

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_passwordKeyPressed
    }
    private void usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyPressed
  if(evt.getKeyCode()==KeyEvent.VK_ENTER){
       password.requestFocus();
    }                                   
    }//GEN-LAST:event_usernameKeyPressed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton reset;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
